### ISSUE TITLE
The `dll:serve` script in the generated package does not work

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-package-generator#87]
## 📝 Provide detailed reproduction steps (if any)

1. Generate a new package (you can use the npm version of the tool).
2. Change `cwd` as the script suggests.
3. `yarn run dll:serve` prints a lot of strings (see: https://github.com/ckeditor/ckeditor5/issues/11092).

### ✔️ Expected result

`yarn run dll:serve` works.

```
$ http-server ./ -o sample/dll.html
Starting up http-server, serving ./

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:8080
  http://192.168.0.13:8080
  http://192.168.0.11:8080
Hit CTRL-C to stop the server
Open: http://127.0.0.1:8080/sample/dll.html
```

### ❌ Actual result

![image](https://user-images.githubusercontent.com/2270764/148746168-25c5fe72-a905-448e-b106-a909cdedcc25.png)

### ❓ Possible solution

* When using yarn, adding the `resolutions` key in pkg.json fixes the problem (see: https://github.com/ckeditor/ckeditor5/commit/a4100bf0e751d3c7caed7aa46f7a89864f22c93c).

## 📃 Other details

* Once you generate a new package, you can modify its `package.json` and reinstall dependencies.
* To avoid executing `dll:serve`, you can see a version of the `colors` package in `node_modules/` or lock files (package-lock.json` or `yarn.lock`)
* A proper fix is needed in [`packages/ckeditor5-package-generator/lib/templates/package.json`](https://github.com/ckeditor/ckeditor5-package-generator/blob/0b01aaf01a7aa80506ec67de81944cea587ab5f0/packages/ckeditor5-package-generator/lib/templates/package.json)

* Node: v14.18.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by przemyslaw-zan** [comment]
Due to a [bug in colors library](https://github.com/Marak/colors.js/issues/285), `http-server` stopped working (which broke wide range of repositories, not just our stuff), but thankfully, fix in `http-server` [is being worked on](https://github.com/http-party/http-server/issues/781). In the meantime, temporary fix is to modify `packages/ckeditor5-package-generator/lib/templates/package.json` as follows:

For `yarn`, add:

```json
"resolutions": {
  "colors": "1.4.0"
},
```

For `npm`, you need to keep in mind that you have to use `npm` [8.3.0](https://github.com/npm/cli/releases/tag/v8.3.0) or later, as it introduced `overrides` that is equivalent to `yarn`'s `resolutions`. Also keep in mind, that latest LTS Version of `node.js` includes `npm 8.1.2`, which does not have this function yet, and [current](https://nodejs.org/en/download/current/) version is required instead. If you have required version, add:

```json
"overrides": {
  "colors": "1.4.0"
},
```

**Comment by pomek** [comment]
https://github.com/http-party/http-server/releases/tag/v14.1.0

Let's bump it here: https://github.com/ckeditor/ckeditor5-package-generator/blob/0b01aaf01a7aa80506ec67de81944cea587ab5f0/packages/ckeditor5-package-generator/lib/templates/package.json#L52
